T457: Uncaught exception ghc-internal:GHC.Internal.Exception.ErrorCall:

Correct
CallStack (from HasCallStack):
  error, called at T457.hs:5:22 in main:Main

HasCallStack backtrace:
  collectBacktraces, called at libraries/ghc-internal/src/GHC/Internal/Exception.hs:92:13 in ghc-internal:GHC.Internal.Exception
  toExceptionWithBacktrace, called at libraries/ghc-internal/src/GHC/Internal/Exception.hs:127:5 in ghc-internal:GHC.Internal.Exception
  error, called at T457.hs:5:22 in main:Main

