T24296: Uncaught exception ghc-internal:GHC.Internal.Exception.ErrorCall:

tricky called with at least two args

HasCallStack backtrace:
  collectBacktraces, called at libraries/ghc-internal/src/GHC/Internal/Exception.hs:91:13 in ghc-internal:GHC.Internal.Exception
  toExceptionWithBacktrace, called at libraries/ghc-internal/src/GHC/Internal/Exception.hs:118:5 in ghc-internal:GHC.Internal.Exception
  error, called at T24296.hs:12:7 in main:Main

