withFile002: user error (test)
HasCallStack backtrace:
CallStack (from HasCallStack):
  collectBacktraces, called at libraries/ghc-internal/src/GHC/Exception.hs:88:13 in ghc-internal:GHC.Exception
  toExceptionWithBacktrace, called at libraries/ghc-internal/src/GHC/IO.hs:258:11 in ghc-internal:GHC.IO
  throwIO, called at libraries/ghc-internal/src/GHC/IO/Exception.hs:315:19 in ghc-internal:GHC.IO.Exception
  ioException, called at libraries/ghc-internal/src/GHC/IO/Exception.hs:319:20 in ghc-internal:GHC.IO.Exception
  ioError, called at libraries/ghc-internal/src/GHC/IO/Handle/FD.hs:172:16 in ghc-internal:GHC.IO.Handle.FD



