Main: Uncaught exception ghc-internal:GHC.Internal.Exception.ErrorCall:

test
CallStack (from HasCallStack):
  error, called at callstack/./Main.hs:4:8 in main:Main

HasCallStack backtrace:
  collectBacktraces, called at libraries/ghc-internal/src/GHC/Internal/Exception.hs:92:13 in ghc-internal:GHC.Internal.Exception
  toExceptionWithBacktrace, called at libraries/ghc-internal/src/GHC/Internal/Exception.hs:127:5 in ghc-internal:GHC.Internal.Exception
  error, called at callstack/./Main.hs:4:8 in main:Main

