cgrun016: Uncaught exception ghc-internal:GHC.Internal.Exception.ErrorCall:

6th call to error
CallStack (from HasCallStack):
  error, called at cgrun016.hs:8:8 in main:Main
