RebindableFailA: Uncaught exception ghc-internal:GHC.Internal.Exception.ErrorCall:

Failed with error

HasCallStack backtrace:
  collectBacktraces, called at libraries/ghc-internal/src/GHC/Internal/Exception.hs:91:13 in ghc-internal:GHC.Internal.Exception
  toExceptionWithBacktrace, called at libraries/ghc-internal/src/GHC/Internal/Exception.hs:118:5 in ghc-internal:GHC.Internal.Exception
  error, called at RebindableFailA.hs:10:10 in main:Main

