conc021: Uncaught exception ghc-internal:GHC.Internal.Exception.ErrorCall:

wurble
CallStack (from HasCallStack):
  error, called at conc021.hs:9:9 in main:Main

HasCallStack backtrace:
  collectBacktraces, called at libraries/ghc-internal/src/GHC/Internal/Exception.hs:92:13 in ghc-internal:GHC.Internal.Exception
  toExceptionWithBacktrace, called at libraries/ghc-internal/src/GHC/Internal/Exception.hs:127:5 in ghc-internal:GHC.Internal.Exception
  error, called at conc021.hs:9:9 in main:Main

